In [140]:
using Statistics
using Flux, Flux.Optimise
using Flux: onehotbatch, onecold, flatten
using MLDatasets: Iris
using Base.Iterators: partition
using CUDA
using Distributions

In [141]:
data = Iris.features();
y = Iris.labels();

In [142]:
function dummy_variables(X)
    values = unique(X)
    arr = Vector{Integer}(undef,length(X))
    for i in 1:length(X)
        j = 1
        for v in values
            if X[i] == v
                arr[i] = j
                break
            end
            j = j + 1
        end
                
    end
    return arr
end

dummy_variables (generic function with 1 method)

In [143]:
normalize(X)=(X .- findmin(X,dims=1)[1]) ./ (findmax(X,dims=1)[1] - findmin(X, dims=1)[1])

normalize (generic function with 1 method)

In [144]:
function f(x)
    if x == 1
        return -1
    else
        return 1
    end
end
        

f (generic function with 1 method)

In [145]:
data[:,1]

4-element Vector{Float64}:
 5.1
 3.5
 1.4
 0.2

In [146]:
y=dummy_variables(y)
y=y[1:100,]
y=[f(i) for i in y]
data = data[:,1:100]
data = normalize(data);

In [147]:
data

4×100 Matrix{Float64}:
 1.0       1.0       1.0       …  1.0       1.0       1.0    1.0
 0.673469  0.595745  0.666667     0.363636  0.326531  0.35   0.340909
 0.244898  0.255319  0.244444     0.659091  0.612245  0.475  0.636364
 0.0       0.0       0.0          0.0       0.0       0.0    0.0

In [217]:
function perceptron(X,y)
    w = ones(size(X)[1])
    for j in 1:1000
        m = 0
        for i in 1:length(w)
            if y[i] * (w' * X[:,i]) <= 0
                w = w + y[i] * X[:,i]
                m = m + 1
            end
        end
        if m == 0
            return w
        end
    end
end 

perceptron (generic function with 1 method)

In [214]:
def perceptron(X, y):
    w = tf.Variable(np.zeros(X.shape[1]).reshape(1,X.shape[1]), dtype=np.float64)
    for j in range(1000):
        m = 0
        for i in range(X.shape[0]):
            if y[i] * (tf.tensordot(w, X[i], axes=1)) <= 0:
                w = w + y[i] * X[i]
                m = m + 1
        print(m)
        if m == 0:
            print("worked!")
            print(w)
            return w          

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [218]:
w=perceptron(data,y)

4-element Vector{Float64}:
 -1.0
 -0.2692140686061659
  0.4997828918801563
  1.0