In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
data = pd.read_csv('./data/weight_height_data.csv',index_col='Index')
data.describe()

Height(Inches)  Weight(Pounds)
count    25000.000000    25000.000000
mean        67.993114      127.079421
std          1.901679       11.660898
min         60.278360       78.014760
25%         66.704397      119.308675
50%         67.995700      127.157750
75%         69.272958      134.892850
max         75.152800      170.924000

In [22]:
data = data.values.T

In [23]:
data[0]-data[0].mean()

array([-2.2098036,  3.5220964,  1.4056264, ..., -3.2945636, -0.4639336,
        0.8844964])

In [26]:
cov = ((data[0]-data[0].mean()) * (data[1]-data[1].mean())).sum() / n

In [27]:
cov

11.150583132400378

In [8]:
var = list()
for i in data:
    n = len(i)
    var.append((1/n)*((i-i.mean())**2).sum())

In [15]:
for i in var:
    print(np.sqrt(i))

1.9016407372498432
11.660664343320782


In [15]:
np.linalg.svd(data)

(array([[-0.46969587, -0.88282829],
        [-0.88282829,  0.46969587]]),
 array([22851.776725  ,   769.44996593]),
 array([[-5.71732895e-03, -6.74281262e-03, -7.33828184e-03, ...,
         -5.89874356e-03, -6.49788800e-03, -6.23995268e-03],
        [-6.50238106e-03,  1.26307120e-03,  1.37876820e-02, ...,
         -2.03898087e-03,  3.26097397e-03, -2.79967142e-03],
        [-6.27084430e-03, -1.43043978e-02,  9.99756701e-01, ...,
         -1.43472652e-05, -9.18613470e-05, -6.30033046e-06],
        ...,
        [-6.03648769e-03,  1.58579852e-03, -1.55680898e-05, ...,
          9.99961268e-01, -3.16625835e-05, -4.22561628e-05],
        [-6.23170966e-03, -3.74431023e-03, -9.26938138e-05, ...,
         -3.12507332e-05,  9.99947420e-01, -3.09394517e-05],
        [-6.43444059e-03,  2.31842203e-03, -7.65157204e-06, ...,
         -4.23042313e-05, -3.14280761e-05,  9.99953478e-01]]))